protocols:
  - id: "httpProtocol"
    type: "http"
    config:
      server_port: 5555 # The server port to be used for HTTP communication
devices:
  - id: "device1" # Unique identifier for the device
    protocol_id: "httpProtocol" # Which publishing protocol the device uses (e.g., HTTP)
    sensors:
      # LOCAL SENSOR
      - id: "randomStringSensor"
        type: "random_string"
        source: "local"
        update_time_ms: 2000
        value_len: 10
        # [NOTE] Parameters like min_val/max_val for numeric or value_len for strings are only allowed when source=local.

    actuators:
      - id: "demoActuator"
        type: "string"
        initial_value: "ON"

independent_communication: True
device_update_delay_ms: 10
