protocols:
  - id: "mqttProtocol"
    type: "mqtt"
    config:
      broker_ip: "192.168.1.106"
      broker_port: 1883
      username: null
      password: null
devices:
  - id: "device1"
    protocol_id: "mqttProtocol"
    sensors:
      - id: "fixedStringSensor"
        type: "fixed_string"
        value: "test-fixed-string"
        update_time_ms: 5000
      - id: "sensor_accel"
        type: "numeric"
        update_time_ms: 1000
        csv_file: "../test/data/accelerometer_data_seconds.csv"
        value_columns: ["accel_x", "accel_y", "accel_z"]
    actuators:
      - id: "demoActuator"
        type: "string"
        initial_value: "ON"
independent_communication: True
device_update_delay_ms: 1000 # Update every 10 seconds if independent_communication is False
